export const LINK_EDIT_DAY = '/edit'
export const LINK_EDIT_BOOKS_DAY = '/EditBooksDay'
export const LINK_EDIT_ENTITY = '/EditEntity'
export const LINK_EDIT_BOOKS_ENTITY = '/editBooksEntity'
export const LINK_STATS = '/stat'
export const DATA_TYPE_DATA = 'Data'
export const DATA_TYPE_BOOKS_DATA = 'BooksData'
